name: K6 Performance Suite CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  performance-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Test Suite
        uses: actions/checkout@v4
        with:
          path: tests-repo

      - name: Checkout API
        uses: actions/checkout@v4
        with:
          repository: Mysterion147/performance-test-api
          path: api-repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start API
        run: |
          cd api-repo
          npm install fastify
          node server.js &

      - name: Wait for API
        run: npx wait-on http://localhost:3000/fast

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 suite
        run: k6 run tests-repo/complete-suite/performance-suite.js

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_files: complete-suite-report.html
          destination_dir: reports